/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { PostContract, PostContractInterface } from "../PostContract";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "contentHash",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "PostCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "contentHash",
        type: "string",
      },
    ],
    name: "createPost",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getPostCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalPosts",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "userPostCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102ee806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806360cd13ea146100515780638e53fb4114610083578063a4c7fafa1461008c578063c7303c61146100b5575b600080fd5b61007161005f366004610145565b60006020819052908152604090205481565b60405190815260200160405180910390f35b61007160015481565b61007161009a366004610145565b6001600160a01b031660009081526020819052604090205490565b6100c86100c336600461018b565b6100ca565b005b3360009081526020819052604081208054916100e58361023c565b9091555050600180549060006100fa8361023c565b9190505550336001600160a01b03167fb5a2d6ecdc9bd09637c1de2e8e02011abe041770e16737ec2adfa54c8e0581c7824260405161013a929190610263565b60405180910390a250565b60006020828403121561015757600080fd5b81356001600160a01b038116811461016e57600080fd5b9392505050565b634e487b7160e01b600052604160045260246000fd5b60006020828403121561019d57600080fd5b813567ffffffffffffffff808211156101b557600080fd5b818401915084601f8301126101c957600080fd5b8135818111156101db576101db610175565b604051601f8201601f19908116603f0116810190838211818310171561020357610203610175565b8160405282815287602084870101111561021c57600080fd5b826020860160208301376000928101602001929092525095945050505050565b60006001820161025c57634e487b7160e01b600052601160045260246000fd5b5060010190565b604081526000835180604084015260005b818110156102915760208187018101516060868401015201610274565b506000606082850101526060601f19601f830116840101915050826020830152939250505056fea264697066735822122088fc9e61fbfca5a1f904001fb168550ae999fc249fef79bfc4fde69714b4849f64736f6c63430008140033";

type PostContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PostContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PostContract__factory extends ContractFactory {
  constructor(...args: PostContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PostContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PostContract__factory {
    return super.connect(runner) as PostContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PostContractInterface {
    return new Interface(_abi) as PostContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PostContract {
    return new Contract(address, _abi, runner) as unknown as PostContract;
  }
}
