/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseElementNFT__factory } from "./BaseElementNFT__factory";
export { BaseMorningGame__factory } from "./BaseMorningGame__factory";
